subProjects:
  - name: subproject1
    version: 1.0.0
    path: ./subproject1
    buildCmd:
      - go build
    dockerfile: ./subproject1/Dockerfile
  - name: subproject2
    version: 2.0.0
    path: ./subproject2
    buildCmd:
      - go build
    dockerfile: ./subproject2/Dockerfile